name = "FrameCapture"
uuid = "3491e0ce-e867-43eb-a6c9-b5be3530cb82"
version = "0.1.0"
authors = ["KonstantinDege <konstantin.dege@outlook.de>"]

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"

[compat]
Colors = "0.13.1"
FileIO = "1.17.1"
FixedPointNumbers = "0.8.5"
