[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
FrameCapture = "3491e0ce-e867-43eb-a6c9-b5be3530cb82"
ImageBase = "c817782e-172a-44cc-b673-b171935fbb9e"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageView = "86fae568-95e7-573e-a6b2-d8a6b900c9ef"

[sources]
FrameCapture = {path = ".."}
